// Copyright (C) 2025 Kampute
//
// Released under the terms of the MIT license.
// See the LICENSE file in the project root for the full license text.

namespace Kampose.Models
{
    using Kampute.DocToolkit.XmlDoc;
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;

    /// <summary>
    /// Represents the audit settings for URL and XML documentation analysis.
    /// </summary>
    public sealed class AuditConfiguration
    {
        /// <summary>
        /// Gets the list of audit options that specify which documentation elements to check.
        /// </summary>
        /// <value>
        /// A list of strings representing the documentation elements to check during the audit process.
        /// By default, only minimum requirements are checked.
        /// </value>
        [JsonConverter(typeof(Support.OverwritingCollectionJsonConverter<HashSet<string>, string>))]
        public HashSet<string> Options { get; init; } = new(StringComparer.OrdinalIgnoreCase)
        {
            nameof(XmlDocInspectionOptions.Required)
        };

        /// <summary>
        /// Gets or sets a value indicating whether to include default public constructors generated by the compiler in the audit process.
        /// </summary>
        /// <value>
        /// <see langword="true"/> to include implicit constructors in audit; otherwise, <see langword="false"/> to omit them.
        /// Default is <see langword="false"/>.
        /// </value>
        public bool IncludeImplicitConstructors { get; set; } = false;

        /// <summary>
        /// Gets or sets a value indicating whether to verify external links found in the XML documentation comments or markdown files.
        /// </summary>
        /// <value>
        /// <see langword="true"/> to verify external links; otherwise, <see langword="false"/>.
        /// Default is <see langword="false"/>.
        /// </value>
        /// <remarks>
        /// Enabling this option may increase the time taken for the audit process, as it involves making network requests to validate
        /// each external link.
        /// </remarks>
        public bool VerifyExternalLinks { get; set; } = false;

        /// <summary>
        /// Gets or sets a value indicating whether to stop documentation generation when audit issues are found.
        /// </summary>
        /// <value>
        /// <see langword="true"/> if documentation generation should stop on audit issues; otherwise, <see langword="false"/>.
        /// Default is <see langword="false"/>.
        /// </value>
        public bool StopOnIssues { get; set; } = false;

        /// <summary>
        /// Gets or sets the inspection options for the XML documentation audit.
        /// </summary>
        /// <value>
        /// A <see cref="XmlDocInspectionOptions"/> value representing the configured audit options.
        /// </value>
        public XmlDocInspectionOptions InspectionOptions
        {
            get
            {
                var result = IncludeImplicitConstructors ? XmlDocInspectionOptions.None : XmlDocInspectionOptions.OmitImplicitlyCreatedConstructors;
                foreach (var option in Options)
                {
                    if (Enum.TryParse<XmlDocInspectionOptions>(option, true, out var parsedOption))
                        result |= parsedOption;
                }
                return result;
            }
            set
            {
                Options.Clear();
                foreach (var option in Enum.GetValues<XmlDocInspectionOptions>())
                {
                    if (value.HasFlag(option) && option is not (XmlDocInspectionOptions.None or XmlDocInspectionOptions.OmitImplicitlyCreatedConstructors))
                        Options.Add(option.ToString());
                }

                IncludeImplicitConstructors = !value.HasFlag(XmlDocInspectionOptions.OmitImplicitlyCreatedConstructors);
            }
        }
    }
}
